# Copyright 2026 SynapsAI Technologies Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
Chat completion type definitions
"""

from typing import Optional, Dict, Any, Union, List, Literal
from pydantic import BaseModel, Field, ConfigDict
from enum import Enum

from .common import APIResponse, FinishReason, Usage


class ChatRole(str, Enum):
    """Chat message roles"""
    SYSTEM = "system"
    USER = "user"
    ASSISTANT = "assistant"
    FUNCTION = "function"
    TOOL = "tool"
    DEVELOPER = "developer"


class ReasoningEffort(str, Enum):
    """Reasoning effort levels for reasoning models (vLLM only)"""
    NONE = "none"
    MINIMAL = "minimal"
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    XHIGH = "xhigh"
    MAX = "max"


class FunctionCall(BaseModel):
    """Function call object (legacy; prefer tool_calls)"""
    name: str
    arguments: str


class ChatCompletionMessageToolCallFunction(BaseModel):
    """The function that the model called."""
    name: str
    arguments: str


class ToolCall(BaseModel):
    """A tool call generated by the model (OpenAI-compatible)."""
    id: str
    type: Literal["function"] = "function"
    function: ChatCompletionMessageToolCallFunction


# OpenAI SDK alias
ChatCompletionMessageToolCall = ToolCall


class DeltaFunctionCall(BaseModel):
    """Partial function call fields in a streaming delta."""
    name: Optional[str] = None
    arguments: Optional[str] = None


class DeltaToolCall(BaseModel):
    """A tool call delta in a streaming response (OpenAI-compatible)."""
    index: int
    id: Optional[str] = None
    type: Optional[Literal["function"]] = None
    function: Optional[DeltaFunctionCall] = None


# OpenAI SDK alias
ChoiceDeltaToolCall = DeltaToolCall


class ChatCompletionNamedToolChoice(BaseModel):
    """Force the model to call a specific function."""
    type: Literal["function"] = "function"
    function: Dict[str, str]


ToolChoice = Union[
    Literal["none", "auto", "required"],
    ChatCompletionNamedToolChoice,
    Dict[str, Any],
]


class ChatMessage(BaseModel):
    """Chat message object"""
    model_config = ConfigDict(extra="ignore")

    role: Union[ChatRole, str]
    content: Optional[str] = None
    name: Optional[str] = None
    refusal: Optional[str] = None
    reasoning: Optional[str] = None
    function_call: Optional[FunctionCall] = None
    tool_calls: Optional[List[ToolCall]] = None
    tool_call_id: Optional[str] = None


class Function(BaseModel):
    """Function definition"""
    name: str
    description: Optional[str] = None
    parameters: Optional[Dict[str, Any]] = None


class Tool(BaseModel):
    """Tool definition"""
    type: Literal["function"] = "function"
    function: Function


class ResponseFormat(BaseModel):
    """Response format specification"""
    type: Literal["text", "json_object"] = "text"


class ChatCompletionRequest(BaseModel):
    """Chat completion request"""
    model: str
    messages: List[ChatMessage]
    temperature: Optional[float] = Field(default=1.0, ge=0.0, le=2.0)
    top_p: Optional[float] = Field(default=1.0, ge=0.0, le=1.0)
    n: Optional[int] = Field(default=1, ge=1)
    stream: Optional[bool] = False
    stop: Optional[Union[str, List[str]]] = None
    max_tokens: Optional[int] = Field(default=None, gt=0)
    presence_penalty: Optional[float] = Field(default=0.0, ge=-2.0, le=2.0)
    frequency_penalty: Optional[float] = Field(default=0.0, ge=-2.0, le=2.0)
    logit_bias: Optional[Dict[str, float]] = None
    functions: Optional[List[Function]] = None
    function_call: Optional[Union[str, Dict[str, str]]] = None
    tools: Optional[List[Tool]] = None
    tool_choice: Optional[ToolChoice] = None
    response_format: Optional[ResponseFormat] = None
    seed: Optional[int] = None
    reasoning_effort: Optional[ReasoningEffort] = None


class CompletionRequest(BaseModel):
    """Completion request"""
    model: str
    prompt: str
    temperature: Optional[float] = Field(default=1.0, ge=0.0, le=2.0)
    top_p: Optional[float] = Field(default=1.0, ge=0.0, le=1.0)
    n: Optional[int] = Field(default=1, ge=1)
    stream: Optional[bool] = False
    stop: Optional[Union[str, List[str]]] = None
    max_tokens: Optional[int] = Field(default=None, gt=0)
    presence_penalty: Optional[float] = Field(default=0.0, ge=-2.0, le=2.0)
    frequency_penalty: Optional[float] = Field(default=0.0, ge=-2.0, le=2.0)
    logit_bias: Optional[Dict[str, float]] = None
    response_format: Optional[ResponseFormat] = None
    seed: Optional[int] = None


class Delta(BaseModel):
    """Delta object for streaming responses"""
    model_config = ConfigDict(extra="ignore")

    role: Optional[Union[ChatRole, str]] = None
    content: Optional[str] = None
    refusal: Optional[str] = None
    reasoning: Optional[str] = None
    function_call: Optional[DeltaFunctionCall] = None
    tool_calls: Optional[List[DeltaToolCall]] = None


# OpenAI SDK alias
ChoiceDelta = Delta


class ChatCompletionChoice(BaseModel):
    """Choice object"""
    model_config = ConfigDict(extra="ignore")

    index: int = Field(default=0)
    message: Optional[ChatMessage] = None
    delta: Optional[Delta] = None
    logprobs: Optional[dict | list[dict]] = None
    finish_reason: Optional[Union[FinishReason, str]] = None


class CompletionChoice(BaseModel):
    """Choice object"""
    index: int = Field(default=0)
    text: str
    logprobs: Optional[dict | list[dict]] = None
    finish_reason: Optional[Union[FinishReason, str]] = None


class ChatCompletionResponse(APIResponse):
    """Chat completion response"""
    model_config = ConfigDict(extra="ignore")

    model: str
    object: str
    choices: List[ChatCompletionChoice]
    system_fingerprint: Optional[str] = None
    usage: Optional[Usage] = None


class CompletionResponse(APIResponse):
    """Completion response"""
    model: str
    object: str
    choices: List[CompletionChoice]
    system_fingerprint: Optional[str] = None
    usage: Optional[Usage] = None


class ChatCompletionChunk(APIResponse):
    """Chat completion chunk for streaming"""
    model_config = ConfigDict(extra="ignore")

    model: str
    object: str
    choices: List[ChatCompletionChoice]
    system_fingerprint: Optional[str] = None
    usage: Optional[Usage] = None


class CompletionChunk(APIResponse):
    """Completion chunk for streaming"""
    model: str
    object: str
    choices: List[CompletionChoice]
    system_fingerprint: Optional[str] = None
    usage: Optional[Usage] = None
